# Generated by Django 6.1.1 on 2026-09-26 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Rating cannot be lower than 0.'), django.core.validators.MaxValueValidator(10.0, message='Rating cannot be higher than 10')])),
                ('cover', models.ImageField(blank=True, upload_to='game_covers/')),
                ('genres', models.ManyToManyField(related_name='games', to='genres.genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='publishers.publisher')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
