# Generated by Django 6.1.1 on 2026-09-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover',
        ),
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
