# Generated by Django 6.1.1 on 2026-10-03 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_cover_game_cover_url'),
        ('genres', '0001_initial'),
        ('publishers', '0003_alter_publisher_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='publishers.publisher'),
        ),
    ]
