# Generated by Django 6.1.1 on 2026-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
