# Generated by Django 6.1.1 on 2026-09-28 10:07

import django.core.validators
import publishers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_alter_publisher_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(publishers.models.current_year)]),
        ),
    ]
